# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to Github pages

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Get files
      uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build:prod
    - name: Add .nojekyll file
      run: touch ./out/.nojekyll
    - name: Change CNAME file
      run: sed -i -e 's/tagion/dev.tagion/g' ./out/CNAME
    - name: Log CNAME file
      run: cat ./out/CNAME
    - name: Push directory to another repository
      uses: cpina/github-action-push-to-another-repository@v1.4.2
      env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
          source-directory: './out'
          destination-github-username: 'tagion'
          destination-repository-name: 'dev-tagion.github.io'
          user-email: tini2n@gmail.com
          target-branch: master
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages-develop
        folder: out